// Generated by scripts/build.ts — do not edit manually
// Project: streaming-wars | Built: 2026-03-06T20:58:46.298Z

export const data = {
  "id": "StreamingWars",
  "title": "Streaming Wars — Subscribers 2010–2024 (Millions)",
  "valueSuffix": "M",
  "fps": 30,
  "topN": 10,
  "transitionFrames": 25,
  "holdFrames": 20,
  "trailingFrames": 60,
  "musicSrc": "Signal Through the Dark.mp3",
  "musicVolume": 0.7,
  "labColors": {
    "Netflix": "#e05252",
    "Hulu": "#4285f4",
    "Amazon Prime Video": "#10a37f",
    "Apple TV+": "#e0e0e0",
    "Disney+": "#4285f4",
    "HBO Max": "#a855f7",
    "Peacock": "#f97316",
    "Paramount+": "#eab308"
  },
  "entries": [
    {
      "model": "Netflix",
      "lab": "Netflix",
      "date": "2010-12-31",
      "mmlu": 20
    },
    {
      "model": "Netflix",
      "lab": "Netflix",
      "date": "2011-12-31",
      "mmlu": 23.7
    },
    {
      "model": "Netflix",
      "lab": "Netflix",
      "date": "2012-12-31",
      "mmlu": 33.3
    },
    {
      "model": "Netflix",
      "lab": "Netflix",
      "date": "2014-12-31",
      "mmlu": 57.4
    },
    {
      "model": "Netflix",
      "lab": "Netflix",
      "date": "2016-12-31",
      "mmlu": 93.8
    },
    {
      "model": "Netflix",
      "lab": "Netflix",
      "date": "2018-12-31",
      "mmlu": 139.3
    },
    {
      "model": "Netflix",
      "lab": "Netflix",
      "date": "2019-12-31",
      "mmlu": 167.1
    },
    {
      "model": "Netflix",
      "lab": "Netflix",
      "date": "2020-12-31",
      "mmlu": 203.7
    },
    {
      "model": "Netflix",
      "lab": "Netflix",
      "date": "2021-12-31",
      "mmlu": 221.8
    },
    {
      "model": "Netflix",
      "lab": "Netflix",
      "date": "2022-12-31",
      "mmlu": 231.3
    },
    {
      "model": "Netflix",
      "lab": "Netflix",
      "date": "2023-12-31",
      "mmlu": 260.3
    },
    {
      "model": "Netflix",
      "lab": "Netflix",
      "date": "2024-12-31",
      "mmlu": 301.6
    },
    {
      "model": "Hulu",
      "lab": "Hulu",
      "date": "2012-12-15",
      "mmlu": 3
    },
    {
      "model": "Hulu",
      "lab": "Hulu",
      "date": "2014-12-15",
      "mmlu": 6
    },
    {
      "model": "Hulu",
      "lab": "Hulu",
      "date": "2016-12-15",
      "mmlu": 12
    },
    {
      "model": "Hulu",
      "lab": "Hulu",
      "date": "2018-12-15",
      "mmlu": 25
    },
    {
      "model": "Hulu",
      "lab": "Hulu",
      "date": "2020-12-15",
      "mmlu": 38.8
    },
    {
      "model": "Hulu",
      "lab": "Hulu",
      "date": "2021-12-15",
      "mmlu": 43.8
    },
    {
      "model": "Hulu",
      "lab": "Hulu",
      "date": "2022-12-15",
      "mmlu": 47.2
    },
    {
      "model": "Hulu",
      "lab": "Hulu",
      "date": "2023-12-15",
      "mmlu": 48.5
    },
    {
      "model": "Hulu",
      "lab": "Hulu",
      "date": "2024-12-15",
      "mmlu": 51
    },
    {
      "model": "Amazon Prime Video",
      "lab": "Amazon Prime Video",
      "date": "2014-12-01",
      "mmlu": 20
    },
    {
      "model": "Amazon Prime Video",
      "lab": "Amazon Prime Video",
      "date": "2016-12-01",
      "mmlu": 54
    },
    {
      "model": "Amazon Prime Video",
      "lab": "Amazon Prime Video",
      "date": "2018-12-01",
      "mmlu": 100
    },
    {
      "model": "Amazon Prime Video",
      "lab": "Amazon Prime Video",
      "date": "2020-12-01",
      "mmlu": 150
    },
    {
      "model": "Amazon Prime Video",
      "lab": "Amazon Prime Video",
      "date": "2021-12-01",
      "mmlu": 175
    },
    {
      "model": "Amazon Prime Video",
      "lab": "Amazon Prime Video",
      "date": "2022-12-01",
      "mmlu": 200
    },
    {
      "model": "Amazon Prime Video",
      "lab": "Amazon Prime Video",
      "date": "2023-12-01",
      "mmlu": 220
    },
    {
      "model": "Amazon Prime Video",
      "lab": "Amazon Prime Video",
      "date": "2024-12-01",
      "mmlu": 230
    },
    {
      "model": "Apple TV+",
      "lab": "Apple TV+",
      "date": "2019-11-15",
      "mmlu": 10
    },
    {
      "model": "Apple TV+",
      "lab": "Apple TV+",
      "date": "2021-11-15",
      "mmlu": 33
    },
    {
      "model": "Apple TV+",
      "lab": "Apple TV+",
      "date": "2023-11-15",
      "mmlu": 55
    },
    {
      "model": "Apple TV+",
      "lab": "Apple TV+",
      "date": "2024-11-15",
      "mmlu": 72
    },
    {
      "model": "Disney+",
      "lab": "Disney+",
      "date": "2019-11-30",
      "mmlu": 26.5
    },
    {
      "model": "Disney+",
      "lab": "Disney+",
      "date": "2020-11-30",
      "mmlu": 86.8
    },
    {
      "model": "Disney+",
      "lab": "Disney+",
      "date": "2021-11-30",
      "mmlu": 118.1
    },
    {
      "model": "Disney+",
      "lab": "Disney+",
      "date": "2022-11-30",
      "mmlu": 164.2
    },
    {
      "model": "Disney+",
      "lab": "Disney+",
      "date": "2023-11-30",
      "mmlu": 150.2
    },
    {
      "model": "Disney+",
      "lab": "Disney+",
      "date": "2024-11-30",
      "mmlu": 157.8
    },
    {
      "model": "HBO Max",
      "lab": "HBO Max",
      "date": "2020-10-31",
      "mmlu": 36
    },
    {
      "model": "HBO Max",
      "lab": "HBO Max",
      "date": "2021-10-31",
      "mmlu": 73.8
    },
    {
      "model": "HBO Max",
      "lab": "HBO Max",
      "date": "2022-10-31",
      "mmlu": 92.9
    },
    {
      "model": "HBO Max",
      "lab": "HBO Max",
      "date": "2023-10-31",
      "mmlu": 95.1
    },
    {
      "model": "HBO Max",
      "lab": "HBO Max",
      "date": "2024-10-31",
      "mmlu": 102.3
    },
    {
      "model": "Peacock",
      "lab": "Peacock",
      "date": "2020-10-15",
      "mmlu": 22
    },
    {
      "model": "Peacock",
      "lab": "Peacock",
      "date": "2021-10-15",
      "mmlu": 28
    },
    {
      "model": "Peacock",
      "lab": "Peacock",
      "date": "2022-10-15",
      "mmlu": 28
    },
    {
      "model": "Peacock",
      "lab": "Peacock",
      "date": "2023-10-15",
      "mmlu": 31
    },
    {
      "model": "Peacock",
      "lab": "Peacock",
      "date": "2024-10-15",
      "mmlu": 36
    },
    {
      "model": "Paramount+",
      "lab": "Paramount+",
      "date": "2021-09-30",
      "mmlu": 21.3
    },
    {
      "model": "Paramount+",
      "lab": "Paramount+",
      "date": "2022-09-30",
      "mmlu": 46
    },
    {
      "model": "Paramount+",
      "lab": "Paramount+",
      "date": "2023-09-30",
      "mmlu": 67.5
    },
    {
      "model": "Paramount+",
      "lab": "Paramount+",
      "date": "2024-09-30",
      "mmlu": 72
    }
  ],
  "storyCards": [
    {
      "trigger": "Netflix",
      "title": "The race begins",
      "body": "Netflix pivots from DVD mail to streaming in 2010 with 20M subscribers. No competitor is close."
    },
    {
      "trigger": "Hulu",
      "title": "Hulu enters the race",
      "body": "Hulu launches a paid subscription tier in 2010, backed by Disney, NBCUniversal, and Fox."
    },
    {
      "trigger": "Amazon Prime Video",
      "title": "Amazon joins the fight",
      "body": "Amazon bundles Prime Video with Prime shipping, quietly building a subscriber base without a standalone price tag."
    },
    {
      "trigger": "Disney+",
      "title": "Disney+ explodes",
      "body": "Disney+ launches November 2019 at $6.99/month. It hits 10M subscribers on day one and keeps accelerating."
    },
    {
      "trigger": "HBO Max",
      "title": "HBO Max arrives",
      "body": "WarnerMedia launches HBO Max in May 2020, combining HBO's prestige catalog with Warner Bros. movies."
    },
    {
      "trigger": "Paramount+",
      "title": "Paramount+ enters",
      "body": "CBS All Access relaunches as Paramount+ in March 2021, adding live sports, news, and a broader film library."
    }
  ]
};
