/**
 * Build script — assembles a barchart.ts from project components.
 *
 * Usage: npm run build -- <project-name>
 * Example: npm run build -- ai-mmlu
 *
 * Reads from:
 *   data/<project>/entries.ts
 *   data/<project>/categories.ts
 *   data/<project>/story-cards.ts
 *   data/<project>/metadata.ts
 *   library/timing.ts
 *   library/music.ts
 *
 * Writes to:
 *   data/<project>/barchart.ts   (permanent archive)
 *   staging/<project>.ts          (ready for workflow)
 */

import fs from 'fs';
import path from 'path';
import { standardTiming } from '../library/timing';
import { signalThroughTheDark } from '../library/music';

const project = process.argv[2];

if (!project) {
  console.error('Usage: npm run build -- <project-name>');
  process.exit(1);
}

const projectDir = path.join('data', project);

if (!fs.existsSync(projectDir)) {
  console.error(`Project folder not found: ${projectDir}`);
  process.exit(1);
}

async function main() {
  // Dynamically import project components
  const { entries }    = await import(`../${projectDir}/entries.ts`);
  const { categories } = await import(`../${projectDir}/categories.ts`);
  const { storyCards } = await import(`../${projectDir}/story-cards.ts`);
  const { metadata }   = await import(`../${projectDir}/metadata.ts`);

  const config = {
    ...metadata,
    ...standardTiming,
    musicSrc: signalThroughTheDark.src,
    musicVolume: signalThroughTheDark.volume,
    labColors: categories,
    entries,
    storyCards,
  };

  const timestamp = new Date().toISOString();
  const output = `\
// Generated by scripts/build.ts — do not edit manually
// Project: ${project} | Built: ${timestamp}

export const data = ${JSON.stringify(config, null, 2)};
`;

  const barchartPath = path.join(projectDir, 'barchart.ts');
  const stagingPath  = path.join('staging', `${project}.ts`);

  fs.writeFileSync(barchartPath, output);
  fs.writeFileSync(stagingPath, output);

  console.log(`✓ Built   ${barchartPath}`);
  console.log(`✓ Staged  ${stagingPath}`);
}

main();
