/**
 * AUTO-GENERATED by scripts/generate-atlantic-audio.mjs — do not edit manually.
 * Re-run the script after regenerating audio to update these values.
 * Last generated: 2026-03-04 (George voice, eleven_multilingual_v2)
 *
 * Format: ATLANTIC_BULLET_DURATIONS_S[slideIndex][bulletIndex]
 * 5 slides × 3 bullets = 15 values, measured from MP3 frame headers.
 */
export const ATLANTIC_BULLET_DURATIONS_S: number[][] = [
  [9.169, 7.367, 4.284], // slide-1: Strategic Stakes
  [10.475, 5.878, 7.158], // slide-2: U-boat Terror
  [10.005, 3.866, 6.296], // slide-3: Atlantic Gap
  [7.262, 7.393, 6.113], // slide-4: Technology War
  [8.202, 6.113, 4.754], // slide-5: Turning Point
];
