/**
 * AUTO-GENERATED by scripts/generate-audio.mjs — do not edit manually.
 * Re-run the script after regenerating audio to update these values.
 * Last generated: 2026-03-03 (George voice, eleven_multilingual_v2)
 */

// Measured durations in seconds (via browser Audio element after generation).
// generate-audio.mjs updates this file automatically after each run.
export const SLIDE_DURATIONS_S: number[] = [
  19.876, // slide-1 — The Strategic Situation of 1940
  25.17,  // slide-2 — The Battle of Britain
  19.37,  // slide-3 — The Atlantic Tonnage War
  21.50,  // slide-4 — Technology & Cryptography
  18.02,  // slide-5 — The Foundation for Liberation
];
